<?php

require 'config.php';
require 'Braintree.php';

Braintree_Configuration::environment('sandbox');
Braintree_Configuration::merchantId(merchantId);
Braintree_Configuration::publicKey(publicKey);
Braintree_Configuration::privateKey(privateKey);

//create a test user on braintree
$result = Braintree_Customer::create(array(
	'firstName' => 'Test',
	'lastName' => 'User',
));

//store customer id generated by braintree
$custid = $result->customer->id;

//generate a token for the dropin UI
$token = Braintree_ClientToken::generate(array(
));

?>

<!DOCTYPE html>
<html>
  <head>
    <title>A Braintree Dropin Payments Example</title>
    <script src="https://js.braintreegateway.com/v2/braintree.js"></script>
    <link rel='stylesheet' href='/components/bootstrap/dist/css/bootstrap.min.css'>
    <link rel='stylesheet' href='/components/bootstrap/dist/css/custom.css'>
  </head>
  <body>
    <div class='container'>

      <div class="col-md-offset-1 col-md-5 col-xs-12 col-sm-6">
        <p>A test user has been created on the Braintree with customer id <?php echo $custid;?></p>
      </div>

      <form class='col-md-5 col-xs-12 col-sm-6' action='step2.php' method='post'>

        <div class="row">
          <div id='checkout'>

          </div>
        </div>

        <div class="row">
          <div class="input-group col-md-6">
            <input type='hidden' value='<?php echo $custid;?>' name='custid'>
            <input type='submit' value='Store Payment Method in Vault' class='btn btn-danger btn-lg'>
          </div>
        </div>

      </form>
    </div>

    <script charset='utf-8'>
      braintree.setup("<?php echo $token;?>", 'dropin', {
        container: 'checkout'
      });
    </script>
  </body>
</html>


<!-- <html>
<body>
    <form id="checkout" method="post" action="proc.php">
      Enter Payment Value: <input type="text" name="amount">
      <input type="submit" value="Pay me">
    </form>
    <script src="https://js.braintreegateway.com/v2/braintree.js"></script>
    <script>
        braintree.setup("<?php echo $token;?>", 'dropin', {
          container: 'checkout',
        });
    </script>
</body>
</html> -->